#zeebe.client.broker.gateway-address=127.0.0.1:26500
#zeebe.client.security.plaintext=true

spring.datasource.url=jdbc:postgresql://localhost:5432/LoanApplication
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
server.port=8080
#zeebe.client.broker.gateway-address=1a8d8e18-4054-4bd2-af ad-6f2adf8c58b8.bru-2.zeebe.camunda.io:443
paymentFailure = false
autoPayFailure = true
zeebe.client.security.plaintext=false 
zeebe.client.cloud.client-id=U_L~ogg51nWrF_z4fLbAVFQS3aZ~GQIB
zeebe.client.cloud.client-secret=2NKLsUvxfCy7B83YD5GTlo4Vw~pKwzgQd72n9_U4NpYUbpPlghYQ_ttg8y3KYCKh
zeebe.client.cloud.auth-server=https://login.cloud.camunda.io/oauth/token
zeebe.client.cloud.cluster-id=1a8d8e18-4054-4bd2-afad-6f2adf8c58b8

#camunda-usertask-timeout-param : 16000000
#
camunda-env=SAASss

app.filesystem.path=D:/loan-process-docs/
app.loans.pdf.path=C:/Users/STS178/Desktop

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=balamanchari@gmail.com
spring.mail.password=fbfo edmj gugw zcfv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Change this value to 9am or 11am if needed and time format is 24 hour
loan.email.scheduled.hour=17
loan.email.scheduled.minute=45

# Runs at 15:29 every day
scheduler.loan.process.cron=0 39 17 * * ?


